server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: secret
    url: jdbc:mysql://localhost:3309/dev
    username: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    show-sql: false
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
  devtools:
    restart:
      enabled: true
